INSERT INTO DATABASE.JOB(NAME, ACTIVE, IDJOB, IDTASK) VALUES ('JOB 01', TRUE, '1', '1');

INSERT INTO DATABASE.PARENT_JOB(NAME, ACTIVE, IDJOB, IDTASK) VALUES ('JOB 02', TRUE, '1', NULL);
INSERT INTO DATABASE.PARENT_JOB(NAME, ACTIVE, IDJOB, IDTASK) VALUES ('JOB 03', TRUE, '3', '2');

INSERT INTO DATABASE.TASK(NAME, WEIGHT, COMPLETED, CREATED_AT) VALUES ('TASK 01', 12, TRUE, SYSDATE);
INSERT INTO DATABASE.TASK(NAME, WEIGHT, COMPLETED, CREATED_AT) VALUES ('TASK 02', 10, TRUE, SYSDATE);
INSERT INTO DATABASE.TASK(NAME, WEIGHT, COMPLETED, CREATED_AT) VALUES ('TASK 03', 13, TRUE, SYSDATE);